services:
  grafana:
    build: .
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_admin_password
    tty: true
    stdin_open: true
    volumes:
      - /:/host:ro,rslave
    pid: "host"
    restart: unless-stopped
